// Automatically generated by astro-icon
// 0947e95c59b15776ad39ce1904ad44bc1b5972607e0b5a1587284e1955cfbd22

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "close"
		| "email"
		| "github"
		| "gitlab"
		| "linkedin"
		| "menu"
		| "moon"
		| "sun"
		| "telegram";
}